name: Unstale Issues

on:
  workflow_dispatch:
      flags:
        type: string
        required: false

  schedule:
    # * is a special character in YAML, so you have to quote this string
    # every day at 9:00
    - cron:  '30 5,17 * * *'

jobs:
  unstale-issues:
    name: unstale issues
    if: |
      github.repository == 'iobroker-bot-orga/stale-handler'
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i
      - run: node ./unstaleIssues.js ${{ github.event.inputs.flags }} 
        env:
          IOBBOT_GITHUB_TOKEN: ${{ secrets.IOBBOT_GITHUB_TOKEN }}
      - name: Send mail on failures
        if: hashFiles('.stale_failures.html') != ''
        uses: dawidd6/action-send-mail@v17
        with:
          server_address: mail.gmx.net
          server_port: 465
          secure: true
          username: iobroker-bot@gmx.at
          password: ${{ secrets.IOBBOT_GMXMAIL }}
          subject: '[iob-bot] Stale handler: failed to comment on issues'
          to: iobroker-bot@gmx.at
          from: ioBroker Bot
          html_body: file://.stale_failures.html
          convert_markdown: false
